name: lando
adopt-info: lando
summary: The best local dev in the galaxy
description: >
  description
grade: stable
confinement: strict
base: core18

parts:
  lando:
    plugin: nodejs
    source: https://github.com/diddledan/lando.git
    override-pull: |
      snapcraftctl pull
      git checkout "$(git describe --tags --abbrev=0 --match v*)"
      snapcraftctl set-version "$(git describe --tags | sed -e 's|^v||')"
    nodejs-version: '12.16.3'
    nodejs-package-manager: yarn

  compose:
    plugin: python
    # https://github.com/docker/compose/blob/1.25.5/setup.py (Docker-supported Python versions)
    python-version: python3
    source: https://github.com/docker/compose.git
    source-tag: '1.25.5'
    source-depth: 1
    build-packages:
      - libffi-dev

plugs:
  docker-executables:
    interface: content
    target: $SNAP/docker
    default-provider: docker:docker-executables

apps:
  lando:
    command: bin/lando
    environment:
      PATH: $PATH:$SNAP/docker/bin
    plugs:
      - docker
      - docker-executables
      - home
      - removable-media
      - network
